[package]
name = "psman-gui"
version = "0.1.0"
description = "psman GUI — 进程/端口/文件占用管理"
edition.workspace = true

[lib]
name = "psman_gui_lib"
crate-type = ["lib", "cdylib", "staticlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon", "image-png"] }
serde.workspace = true
serde_json.workspace = true
sysinfo.workspace = true
windows.workspace = true
psman = { path = ".." }
